ARG ore_plus_version=latest
FROM env_ore_plus_debug:${ore_plus_version}

MAINTAINER Francis Duffy
LABEL Description="Build zlib debug."

# Argument for number of cores to use while building
ARG num_cores

# Exclusions are performed by .dockerignore
COPY . /lib_src/zlib

RUN cd /lib_src/zlib \
  && find -regex ".*\.\(sh\|in\|ac\|am\)" -exec dos2unix {} ';' \
  && dos2unix configure \
  && CFLAGS="-O0 -g" ./configure --debug \
  && make -j ${num_cores} \
  && make install \
  && cd / \
  && ldconfig

CMD bash
